heat_template_version: 2016-10-14

description: Este stack eh de treino

parameters:
  image:
    type: string
    description: Imagem da VM

resources:
  vm:
    type: OS::Nova::Server
    properties: 
      name: stack-treino
      flavor: m1.tiny
      image: { get_param: image }
      networks:
        - network: net

  volume:
    type: OS::Cinder::Volume
    properties:
      size: 1
      name: vol-stack-treino

  attach_vol:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: vm }
      volume_id: { get_resource: volume }
      mountpoint: /dev/vdb
      

outputs:
  ip_vm:
    description: IP da VM
    value: { get_attr: [ vm , first_address ] }
